// Image module declarations, committed on purpose.
//
// next-env.d.ts carries `/// <reference types="next/image-types/global" />`,
// which is what makes `import logo from "../../public/logo.png"` type-check.
// That file is gitignored by Next.js's own default (.gitignore line 37) and is
// regenerated by `next dev` / `next build`, so it exists on every developer
// machine and on no fresh checkout.
//
// CI runs `npm run check` (tsc) BEFORE `npm run build`, so on CI the type check
// happens before anything regenerates next-env.d.ts, and src/app/og/route.tsx
// fails with TS2307 on its logo.png import. The failure is invisible locally
// for exactly the same reason: the file is already there.
//
// Reproduce with: mv next-env.d.ts /tmp && npx tsc --noEmit
//
// Committing next-env.d.ts itself is the obvious-looking fix and is worse: it
// references ./.next/types/routes.d.ts, which only exists after a build, so it
// trades this error for a different one. Declaring the asset modules here is
// independent of build order and of whether next-env.d.ts happens to exist.
declare module "*.png" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.jpg" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.jpeg" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.webp" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.avif" {
  const content: import("next/image").StaticImageData;
  export default content;
}
